# Generated by Django 6.0.5 on 2026-05-26 00:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('requirements', '0001_initial'),
        ('testplans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=180)),
                ('preconditions', models.TextField(blank=True)),
                ('steps', models.TextField()),
                ('expected_result', models.TextField()),
                ('priority', models.CharField(choices=[('LOW', 'Baja'), ('MEDIUM', 'Media'), ('HIGH', 'Alta'), ('CRITICAL', 'Critica')], default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('READY', 'Listo'), ('OBSOLETE', 'Obsoleto')], default='DRAFT', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_cases', to='requirements.requirement')),
                ('test_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='testplans.testplan')),
            ],
            options={
                'ordering': ['test_plan', 'code'],
                'unique_together': {('test_plan', 'code')},
            },
        ),
    ]
