# Generated by Django 6.0.5 on 2026-05-26 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='testcase',
            name='level',
            field=models.CharField(choices=[('UNIT', 'Unitaria'), ('INTEGRATION', 'Integración'), ('SYSTEM', 'Sistema'), ('ACCEPTANCE', 'Aceptación')], default='SYSTEM', max_length=30),
        ),
        migrations.AddField(
            model_name='testcase',
            name='technique',
            field=models.CharField(choices=[('EQUIVALENCE', 'Partición de Equivalencia'), ('BOUNDARY', 'Valores Límite'), ('BLACK_BOX', 'Caja Negra'), ('WHITE_BOX', 'Caja Blanca'), ('EXPLORATORY', 'Exploratoria')], default='BLACK_BOX', max_length=30),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Baja'), ('MEDIUM', 'Media'), ('HIGH', 'Alta'), ('CRITICAL', 'Crítica')], default='MEDIUM', max_length=20),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('PASSED', 'Passed'), ('FAILED', 'Failed'), ('BLOCKED', 'Bloqueado')], default='PENDING', max_length=20),
        ),
    ]
