# Generated by Django 6.0.5 on 2026-06-08 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0002_testcase_description_testcase_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('PASSED', 'Pasado'), ('FAILED', 'Fallido'), ('BLOCKED', 'Bloqueado')], default='PENDING', max_length=20),
        ),
    ]
