# Generated by Django 6.0.5 on 2026-06-14 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0003_alter_testcase_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='steps_data',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='testcase',
            name='test_data',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='testcase',
            name='version',
            field=models.CharField(default='1.0', max_length=20),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='technique',
            field=models.CharField(choices=[('EQUIVALENCE', 'Partición de Equivalencia'), ('BOUNDARY', 'Valores Límite'), ('DECISION_TABLE', 'Tabla de Decisión'), ('STATE_TRANSITION', 'Transición de Estados'), ('USE_CASE', 'Casos de Uso'), ('EXPERIENCE', 'Basada en Experiencia'), ('BLACK_BOX', 'Caja Negra'), ('WHITE_BOX', 'Caja Blanca'), ('EXPLORATORY', 'Exploratoria')], default='BLACK_BOX', max_length=30),
        ),
    ]
