# Generated by Django 6.0.5 on 2026-08-04 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0005_testcase_covered_risks'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='execution_type',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('AUTOMATED', 'Automatizada')], default='MANUAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='status',
            field=models.CharField(choices=[('PENDING', 'En Redacción'), ('READY', 'Listo para Ejecutar'), ('RUNNING', 'Ejecutando'), ('PASSED', 'Completado'), ('FAILED', 'Fallido'), ('BLOCKED', 'Bloqueado')], default='PENDING', max_length=20),
        ),
    ]
