# Generated by Django 6.0.5 on 2026-08-05 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0006_testcase_execution_type_alter_testcase_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='custom_technique',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='technique',
            field=models.CharField(choices=[('EQUIVALENCE', 'Partición de Equivalencia'), ('BOUNDARY', 'Valores Límite'), ('DECISION_TABLE', 'Tabla de Decisión'), ('STATE_TRANSITION', 'Transición de Estados'), ('USE_CASE', 'Casos de Uso'), ('EXPERIENCE', 'Basada en Experiencia'), ('BLACK_BOX', 'Caja Negra'), ('WHITE_BOX', 'Caja Blanca'), ('EXPLORATORY', 'Exploratoria'), ('OTHER', 'Otra')], default='BLACK_BOX', max_length=30),
        ),
    ]
