# Generated by Django 6.0.5 on 2026-09-18 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testcases', '0009_testcase_reexecution_requested'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='requirement_needs_revalidation',
            field=models.BooleanField(default=False, help_text='Indica si el requisito asociado necesita revalidación tras cambios.'),
        ),
    ]
