# Generated by Django 6.0.5 on 2026-05-26 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defects', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='defect',
            name='code',
            field=models.CharField(default='DEF-000', max_length=40),
        ),
        migrations.AddField(
            model_name='defect',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Baja'), ('MEDIUM', 'Media'), ('HIGH', 'Alta'), ('CRITICAL', 'Crítica')], default='MEDIUM', max_length=20),
        ),
        migrations.AlterField(
            model_name='defect',
            name='severity',
            field=models.CharField(choices=[('LOW', 'Baja'), ('MEDIUM', 'Media'), ('HIGH', 'Alta'), ('CRITICAL', 'Crítica')], default='MEDIUM', max_length=20),
        ),
        migrations.AlterField(
            model_name='defect',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Fix'), ('RESOLVED', 'Resuelto'), ('CLOSED', 'Closed')], default='OPEN', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='defect',
            unique_together={('project', 'code')},
        ),
    ]
