# Generated by Django 6.0.5 on 2026-06-08 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defects', '0002_defect_code_defect_priority_alter_defect_severity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defect',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Abierto'), ('IN_PROGRESS', 'En Progreso'), ('RESOLVED', 'Resuelto'), ('CLOSED', 'Cerrado')], default='OPEN', max_length=20),
        ),
    ]
