# Generated by Django 6.0.5 on 2026-06-09 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defects', '0003_alter_defect_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='defect',
            name='steps_to_reproduce',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='defect',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Abierto'), ('ANALYSIS', 'En analisis'), ('IN_PROGRESS', 'En correccion'), ('PENDING_CONFIRMATION', 'Pendiente de confirmacion'), ('CLOSED', 'Cerrado'), ('REJECTED', 'Rechazado'), ('DUPLICATED', 'Duplicado')], default='OPEN', max_length=20),
        ),
        migrations.CreateModel(
            name='DefectHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('OPEN', 'Abierto'), ('ANALYSIS', 'En analisis'), ('IN_PROGRESS', 'En correccion'), ('PENDING_CONFIRMATION', 'Pendiente de confirmacion'), ('CLOSED', 'Cerrado'), ('REJECTED', 'Rechazado'), ('DUPLICATED', 'Duplicado')], max_length=30)),
                ('severity', models.CharField(choices=[('LOW', 'Baja'), ('MEDIUM', 'Media'), ('HIGH', 'Alta'), ('CRITICAL', 'Crítica')], max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Baja'), ('MEDIUM', 'Media'), ('HIGH', 'Alta'), ('CRITICAL', 'Crítica')], max_length=20)),
                ('change_reason', models.CharField(blank=True, max_length=180)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_defect_history', to=settings.AUTH_USER_MODEL)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defect_history_changes', to=settings.AUTH_USER_MODEL)),
                ('defect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='defects.defect')),
            ],
            options={
                'ordering': ['defect', '-created_at'],
            },
        ),
    ]
