# Generated by Django 6.0.5 on 2026-07-31 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defects', '0004_defect_steps_to_reproduce_alter_defect_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defect',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Abierto'), ('ANALYSIS', 'En análisis'), ('IN_PROGRESS', 'En corrección'), ('PENDING_CONFIRMATION', 'Pendiente de confirmación'), ('CLOSED', 'Cerrado'), ('REJECTED', 'Rechazado'), ('DUPLICATED', 'Duplicado')], default='OPEN', max_length=20),
        ),
        migrations.AlterField(
            model_name='defecthistory',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Abierto'), ('ANALYSIS', 'En análisis'), ('IN_PROGRESS', 'En corrección'), ('PENDING_CONFIRMATION', 'Pendiente de confirmación'), ('CLOSED', 'Cerrado'), ('REJECTED', 'Rechazado'), ('DUPLICATED', 'Duplicado')], max_length=30),
        ),
    ]
