# Generated by Django 6.0.5 on 2026-08-05 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defects', '0005_alter_defect_status_alter_defecthistory_status'),
        ('testcases', '0007_testcase_custom_technique_alter_testcase_technique'),
    ]

    operations = [
        migrations.AddField(
            model_name='defect',
            name='test_case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='defects', to='testcases.testcase'),
        ),
        migrations.AlterField(
            model_name='defect',
            name='severity',
            field=models.CharField(choices=[('LOW', 'Baja'), ('MEDIUM', 'Media'), ('HIGH', 'Alta')], default='MEDIUM', max_length=20),
        ),
        migrations.AlterField(
            model_name='defect',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Abierto'), ('IN_PROGRESS', 'En progreso'), ('RESOLVED', 'Resuelto'), ('CLOSED', 'Cerrado'), ('REOPENED', 'Reabierto')], default='OPEN', max_length=20),
        ),
        migrations.AlterField(
            model_name='defecthistory',
            name='severity',
            field=models.CharField(choices=[('LOW', 'Baja'), ('MEDIUM', 'Media'), ('HIGH', 'Alta')], max_length=20),
        ),
        migrations.AlterField(
            model_name='defecthistory',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Abierto'), ('IN_PROGRESS', 'En progreso'), ('RESOLVED', 'Resuelto'), ('CLOSED', 'Cerrado'), ('REOPENED', 'Reabierto')], max_length=30),
        ),
    ]
