[pytest]
DJANGO_SETTINGS_MODULE = config.settings.testing
pythonpath = src
python_files = tests.py test_*.py *_tests.py
addopts = -ra -v --cov=src/apps --cov=src/config --cov-report=term-missing:skip-covered --basetemp=.pytest_tmp
