# Generated by Django 6.0.5 on 2026-06-09 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defects', '0004_defect_steps_to_reproduce_alter_defect_status_and_more'),
        ('executions', '0002_execution_audit_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='testexecution',
            name='execution_type',
            field=models.CharField(choices=[('NORMAL', 'Ejecucion funcional'), ('CONFIRMATION', 'Prueba de confirmacion'), ('REGRESSION', 'Prueba de regresion')], default='NORMAL', max_length=20),
        ),
        migrations.AddField(
            model_name='testexecution',
            name='planned_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testexecution',
            name='related_defect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_executions', to='defects.defect'),
        ),
    ]
