# Generated by Django 6.0.5 on 2026-06-15 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executions', '0003_testexecution_execution_type_and_more'),
        ('requirements', '0003_requirementversion'),
        ('testcases', '0004_testcase_steps_data_testcase_test_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testexecution',
            name='browser',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='testexecution',
            name='duration_seconds',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='testexecution',
            name='environment_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='testexecution',
            name='execution_mode',
            field=models.CharField(choices=[('MANUAL', 'Manual controlada'), ('SEMI_AUTOMATED', 'Semi-automatizada')], default='MANUAL', max_length=20),
        ),
        migrations.AddField(
            model_name='testexecution',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testexecution',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testexecution',
            name='technical_log',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='testexecution',
            name='result',
            field=models.CharField(choices=[('NOT_RUN', 'No ejecutado'), ('RUNNING', 'En ejecucion'), ('PASSED', 'Aprobado'), ('FAILED', 'Fallido'), ('BLOCKED', 'Bloqueado'), ('ERROR', 'Error tecnico')], default='NOT_RUN', max_length=20),
        ),
        migrations.CreateModel(
            name='AutomatedValidationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('step_number', models.PositiveIntegerField(default=1)),
                ('name', models.CharField(max_length=180)),
                ('validation_type', models.CharField(choices=[('FIELD_REQUIRED', 'Campo obligatorio'), ('EMAIL_FORMAT', 'Formato de correo'), ('MAX_LENGTH', 'Longitud maxima'), ('MIN_LENGTH', 'Longitud minima'), ('TEXT_VISIBLE', 'Texto visible'), ('ELEMENT_VISIBLE', 'Elemento visible'), ('REDIRECT_URL', 'Redireccion URL'), ('HTTP_STATUS', 'Estado HTTP'), ('BUTTON_DISABLED', 'Boton deshabilitado'), ('FORM_SUBMISSION_BLOCKED', 'Envio de formulario bloqueado')], max_length=40)),
                ('target_url', models.URLField()),
                ('selector_type', models.CharField(blank=True, choices=[('CSS', 'CSS'), ('ID', 'ID'), ('NAME', 'Name'), ('XPATH', 'XPath')], max_length=10)),
                ('selector_value', models.CharField(blank=True, max_length=500)),
                ('secondary_selector_value', models.CharField(blank=True, max_length=500)),
                ('input_value', models.TextField(blank=True)),
                ('expected_value', models.CharField(blank=True, max_length=500)),
                ('expected_text', models.CharField(blank=True, max_length=500)),
                ('min_length', models.PositiveIntegerField(blank=True, null=True)),
                ('max_length', models.PositiveIntegerField(blank=True, null=True)),
                ('expected_url', models.URLField(blank=True)),
                ('expected_http_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('timeout_seconds', models.PositiveSmallIntegerField(default=10)),
                ('browser', models.CharField(default='chromium', max_length=30)),
                ('capture_evidence', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='automated_rules', to='requirements.requirement')),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automated_rules', to='testcases.testcase')),
            ],
            options={
                'ordering': ['test_case', 'step_number', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AutomatedExecutionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('NOT_RUN', 'No ejecutado'), ('RUNNING', 'En ejecucion'), ('PASSED', 'Aprobado'), ('FAILED', 'Fallido'), ('BLOCKED', 'Bloqueado'), ('ERROR', 'Error tecnico')], max_length=20)),
                ('expected_behavior', models.TextField(blank=True)),
                ('actual_behavior', models.TextField(blank=True)),
                ('input_used', models.TextField(blank=True)),
                ('technical_log', models.TextField(blank=True)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='automation_screenshots/')),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('test_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automated_results', to='executions.testexecution')),
                ('validation_rule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='execution_results', to='executions.automatedvalidationrule')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestStepExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('step_number', models.PositiveIntegerField()),
                ('action', models.TextField()),
                ('expected_result', models.TextField()),
                ('obtained_result', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('NOT_RUN', 'No ejecutado'), ('RUNNING', 'En ejecucion'), ('PASSED', 'Aprobado'), ('FAILED', 'Fallido'), ('BLOCKED', 'Bloqueado'), ('ERROR', 'Error tecnico')], max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('evidence_file', models.FileField(blank=True, null=True, upload_to='step_evidence/')),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='execution_screenshots/')),
                ('execution_log', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('test_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='step_executions', to='executions.testexecution')),
            ],
            options={
                'ordering': ['step_number', 'created_at'],
            },
        ),
    ]
