# Generated by Django 6.0.5 on 2026-07-31 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executions', '0004_testexecution_browser_testexecution_duration_seconds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automatedexecutionresult',
            name='status',
            field=models.CharField(choices=[('NOT_RUN', 'No ejecutado'), ('RUNNING', 'En ejecucion'), ('PASSED', 'Aprobado'), ('FAILED', 'Fallido'), ('BLOCKED', 'Bloqueado'), ('ERROR', 'Error técnico')], max_length=20),
        ),
        migrations.AlterField(
            model_name='automatedvalidationrule',
            name='validation_type',
            field=models.CharField(choices=[('FIELD_REQUIRED', 'Campo obligatorio'), ('EMAIL_FORMAT', 'Formato de correo'), ('MAX_LENGTH', 'Longitud máxima'), ('MIN_LENGTH', 'Longitud mínima'), ('TEXT_VISIBLE', 'Texto visible'), ('ELEMENT_VISIBLE', 'Elemento visible'), ('REDIRECT_URL', 'Redireccion URL'), ('HTTP_STATUS', 'Estado HTTP'), ('BUTTON_DISABLED', 'Boton deshabilitado'), ('FORM_SUBMISSION_BLOCKED', 'Envio de formulario bloqueado')], max_length=40),
        ),
        migrations.AlterField(
            model_name='testexecution',
            name='execution_type',
            field=models.CharField(choices=[('NORMAL', 'Ejecución funcional'), ('CONFIRMATION', 'Prueba de confirmación'), ('REGRESSION', 'Prueba de regresion')], default='NORMAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='testexecution',
            name='result',
            field=models.CharField(choices=[('NOT_RUN', 'No ejecutado'), ('RUNNING', 'En ejecucion'), ('PASSED', 'Aprobado'), ('FAILED', 'Fallido'), ('BLOCKED', 'Bloqueado'), ('ERROR', 'Error técnico')], default='NOT_RUN', max_length=20),
        ),
        migrations.AlterField(
            model_name='testexecution',
            name='review_status',
            field=models.CharField(choices=[('PENDING', 'Pendiente de revisión'), ('VALIDATED', 'Validada'), ('REJECTED', 'Rechazada'), ('NEEDS_FIX', 'Requiere corrección')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='teststepexecution',
            name='status',
            field=models.CharField(choices=[('NOT_RUN', 'No ejecutado'), ('RUNNING', 'En ejecucion'), ('PASSED', 'Aprobado'), ('FAILED', 'Fallido'), ('BLOCKED', 'Bloqueado'), ('ERROR', 'Error técnico')], max_length=20),
        ),
    ]
