# Generated by Django 6.0.5 on 2026-08-03 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executions', '0005_alter_automatedexecutionresult_status_and_more'),
        ('requirements', '0003_requirementversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automatedexecutionresult',
            name='validation_rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_results', to='executions.automatedvalidationrule'),
        ),
        migrations.AlterField(
            model_name='automatedvalidationrule',
            name='requirement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automated_rules', to='requirements.requirement'),
        ),
    ]
