# Generated by Django 6.0.5 on 2026-08-04 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executions', '0006_alter_automatedexecutionresult_validation_rule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='automatedvalidationrule',
            name='action_type',
            field=models.CharField(blank=True, choices=[('OPEN_URL', 'Abrir URL'), ('CLICK', 'Hacer clic'), ('FILL_TEXT', 'Ingresar texto'), ('SELECT_OPTION', 'Seleccionar opción'), ('CHECK', 'Marcar checkbox'), ('UNCHECK', 'Desmarcar checkbox'), ('WAIT', 'Esperar'), ('VERIFY_ELEMENT', 'Verificar elemento visible'), ('VERIFY_TEXT', 'Verificar texto visible'), ('VERIFY_URL', 'Verificar URL'), ('VERIFY_VALUE', 'Verificar valor')], max_length=30),
        ),
        migrations.AddField(
            model_name='automatedvalidationrule',
            name='is_critical',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='automatedvalidationrule',
            name='validation_type',
            field=models.CharField(blank=True, choices=[('FIELD_REQUIRED', 'Campo obligatorio'), ('EMAIL_FORMAT', 'Formato de correo'), ('MAX_LENGTH', 'Longitud máxima'), ('MIN_LENGTH', 'Longitud mínima'), ('TEXT_VISIBLE', 'Texto visible'), ('ELEMENT_VISIBLE', 'Elemento visible'), ('REDIRECT_URL', 'Redireccion URL'), ('HTTP_STATUS', 'Estado HTTP'), ('BUTTON_DISABLED', 'Boton deshabilitado'), ('FORM_SUBMISSION_BLOCKED', 'Envio de formulario bloqueado')], max_length=40),
        ),
        migrations.AlterField(
            model_name='testexecution',
            name='execution_mode',
            field=models.CharField(choices=[('MANUAL', 'Manual controlada'), ('SEMI_AUTOMATED', 'Semi-automatizada'), ('AUTOMATED', 'Automatizada')], default='MANUAL', max_length=20),
        ),
    ]
