# Generated by Django 6.0.5 on 2026-08-04 01:41

from django.db import migrations, models


def forward_convert_semi_automated(apps, schema_editor):
    TestExecution = apps.get_model('executions', 'TestExecution')
    TestExecution.objects.filter(execution_mode='SEMI_AUTOMATED').update(execution_mode='AUTOMATED')


class Migration(migrations.Migration):

    dependencies = [
        ('executions', '0007_automatedvalidationrule_action_type_and_more'),
    ]

    operations = [
        migrations.RunPython(forward_convert_semi_automated, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='automatedvalidationrule',
            name='browser',
        ),
        migrations.RemoveField(
            model_name='automatedvalidationrule',
            name='capture_evidence',
        ),
        migrations.RemoveField(
            model_name='automatedvalidationrule',
            name='expected_http_status',
        ),
        migrations.RemoveField(
            model_name='automatedvalidationrule',
            name='expected_text',
        ),
        migrations.RemoveField(
            model_name='automatedvalidationrule',
            name='expected_url',
        ),
        migrations.RemoveField(
            model_name='automatedvalidationrule',
            name='max_length',
        ),
        migrations.RemoveField(
            model_name='automatedvalidationrule',
            name='min_length',
        ),
        migrations.RemoveField(
            model_name='automatedvalidationrule',
            name='secondary_selector_value',
        ),
        migrations.RemoveField(
            model_name='automatedvalidationrule',
            name='selector_type',
        ),
        migrations.RemoveField(
            model_name='automatedvalidationrule',
            name='validation_type',
        ),
        migrations.AlterField(
            model_name='testexecution',
            name='execution_mode',
            field=models.CharField(choices=[('MANUAL', 'Manual controlada'), ('AUTOMATED', 'Automatizada')], default='MANUAL', max_length=20),
        ),
    ]
