# Generated by Django 6.0.5 on 2026-08-04 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executions', '0008_remove_automatedvalidationrule_browser_and_more'),
        ('testcases', '0006_testcase_execution_type_alter_testcase_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='automatedexecutionresult',
            name='comparison_type',
            field=models.CharField(blank=True, choices=[('EXACT', 'Exacto'), ('CONTAINS', 'Contiene'), ('REGEX', 'Expresión regular')], max_length=20),
        ),
        migrations.AddField(
            model_name='automatedvalidationrule',
            name='comparison_type',
            field=models.CharField(blank=True, choices=[('EXACT', 'Exacto'), ('CONTAINS', 'Contiene'), ('REGEX', 'Expresión regular')], default='EXACT', max_length=20),
        ),
        migrations.AlterField(
            model_name='automatedvalidationrule',
            name='action_type',
            field=models.CharField(blank=True, choices=[('OPEN_URL', 'Abrir URL'), ('FILL_TEXT', 'Escribir'), ('CLICK', 'Click'), ('VERIFY', 'Verificar'), ('WAIT', 'Esperar')], max_length=30),
        ),
        migrations.AlterField(
            model_name='automatedvalidationrule',
            name='target_url',
            field=models.URLField(blank=True),
        ),
        migrations.CreateModel(
            name='TestData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=120)),
                ('value', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_data_vars', to='testcases.testcase')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('test_case', 'key')},
            },
        ),
    ]
