# Generated by Django 6.0.5 on 2026-09-11 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('executions', '0010_testexecution_approval_percentage'),
        ('projects', '0002_project_tutor'),
        ('testcases', '0008_testcase_version'),
        ('testplans', '0007_remove_testplan_base_document'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=40)),
                ('build_number', models.CharField(blank=True, max_length=80)),
                ('commit_sha', models.CharField(blank=True, max_length=64)),
                ('branch', models.CharField(blank=True, max_length=120)),
                ('repository_url', models.URLField(blank=True)),
                ('environment', models.CharField(choices=[('LOCAL', 'Local'), ('QA', 'QA'), ('STAGING', 'Staging'), ('PRODUCTION', 'Producción')], default='QA', max_length=20)),
                ('checksum', models.CharField(blank=True, max_length=128)),
                ('release_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_builds', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='builds', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='testexecution',
            name='build',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='executions.buildartifact'),
        ),
        migrations.CreateModel(
            name='TestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('code', models.CharField(max_length=40, unique=True)),
                ('run_type', models.CharField(choices=[('FUNCTIONAL', 'Funcional'), ('REGRESSION', 'Regresión'), ('CONFIRMATION', 'Confirmación'), ('SMOKE', 'Smoke test'), ('ACCEPTANCE', 'Aceptación')], default='FUNCTIONAL', max_length=20)),
                ('status', models.CharField(choices=[('PLANNED', 'Planificada'), ('RUNNING', 'En ejecución'), ('PAUSED', 'Pausada'), ('COMPLETED', 'Completada'), ('CANCELLED', 'Cancelada')], default='PLANNED', max_length=20)),
                ('verdict', models.CharField(choices=[('PENDING', 'Pendiente'), ('PASSED', 'Aprobada'), ('FAILED', 'Fallida'), ('BLOCKED', 'Bloqueada')], default='PENDING', max_length=20)),
                ('environment', models.CharField(max_length=180)),
                ('scope', models.TextField(blank=True)),
                ('exit_notes', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('build', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_runs', to='executions.buildartifact')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_test_runs', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_runs', to='projects.project')),
                ('test_cases', models.ManyToManyField(blank=True, related_name='test_runs', to='testcases.testcase')),
                ('test_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='test_runs', to='testplans.testplan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='testexecution',
            name='test_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executions', to='executions.testrun'),
        ),
        migrations.AddConstraint(
            model_name='buildartifact',
            constraint=models.UniqueConstraint(fields=('project', 'version', 'build_number'), name='unique_project_build_version'),
        ),
    ]
