# Generated by Django 5.2.15 on 2026-07-31 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_tutor_from_members(apps, schema_editor):
    Project = apps.get_model('projects', 'Project')
    for project in Project.objects.all().iterator(chunk_size=500):
        tutor = project.members.filter(role='TEACHER').first()
        if tutor and project.tutor_id is None:
            project.tutor = tutor
            project.save(update_fields=['tutor'])


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutored_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(backfill_tutor_from_members, migrations.RunPython.noop),
    ]
