# Generated by Django 6.0.5 on 2026-05-26 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('SUMMARY', 'Resumen'), ('COVERAGE', 'Cobertura'), ('DEFECTS', 'Defectos'), ('EXECUTION', 'Ejecución')], max_length=20),
        ),
    ]
