# Generated by Django 6.0.5 on 2026-06-09 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('reports', '0002_alter_report_report_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filename', models.CharField(max_length=180)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('downloaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_downloads', to='projects.project')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='reports.report')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
