# Generated by Django 6.0.5 on 2026-06-15 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_reportdownload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_type',
            field=models.CharField(choices=[('SUMMARY', 'Resumen'), ('COVERAGE', 'Cobertura'), ('DEFECTS', 'Defectos'), ('EXECUTION', 'Ejecución'), ('FINAL', 'Informe general final')], max_length=20),
        ),
    ]
