# Generated by Django 6.0.5 on 2026-05-26 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('requirements', '0001_initial'),
        ('testcases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TraceabilityLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rationale', models.TextField(blank=True)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traceability_links', to='requirements.requirement')),
                ('test_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traceability_links', to='testcases.testcase')),
            ],
            options={
                'unique_together': {('requirement', 'test_case')},
            },
        ),
    ]
