# Generated by Django 6.0.5 on 2026-05-26 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirement',
            name='requirement_type',
            field=models.CharField(choices=[('FUNCTIONAL', 'Funcional'), ('NON_FUNCTIONAL', 'No funcional')], default='FUNCTIONAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Baja'), ('MEDIUM', 'Media'), ('HIGH', 'Alta'), ('CRITICAL', 'Crítica')], default='MEDIUM', max_length=20),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('REVIEW', 'En revisión'), ('APPROVED', 'Aprobado'), ('CHANGED', 'Cambiado'), ('RETIRED', 'Retirado')], default='PENDING', max_length=20),
        ),
    ]
