# Generated by Django 6.0.5 on 2026-06-09 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0002_requirement_requirement_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequirementVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField()),
                ('requirement_type', models.CharField(choices=[('FUNCTIONAL', 'Funcional'), ('NON_FUNCTIONAL', 'No funcional')], max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Baja'), ('MEDIUM', 'Media'), ('HIGH', 'Alta'), ('CRITICAL', 'Crítica')], max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('REVIEW', 'En revisión'), ('APPROVED', 'Aprobado'), ('CHANGED', 'Cambiado'), ('RETIRED', 'Retirado')], max_length=20)),
                ('change_reason', models.CharField(blank=True, max_length=180)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='requirements.requirement')),
            ],
            options={
                'ordering': ['requirement', '-version_number'],
                'unique_together': {('requirement', 'version_number')},
            },
        ),
    ]
