# Generated by Django 5.2.15 on 2026-08-04 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requirements', '0003_requirementversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirement',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('REVIEW', 'En revisión'), ('APPROVED', 'Aprobado')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='requirementversion',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pendiente'), ('REVIEW', 'En revisión'), ('APPROVED', 'Aprobado')], max_length=20),
        ),
    ]
