# Generated by Django 6.0.5 on 2026-05-26 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='code',
            field=models.CharField(default='INC-000', max_length=40),
        ),
        migrations.AddField(
            model_name='incident',
            name='impact',
            field=models.CharField(choices=[('LOW', 'Bajo'), ('MEDIUM', 'Medio'), ('HIGH', 'Alto')], default='MEDIUM', max_length=20),
        ),
        migrations.AddField(
            model_name='incident',
            name='probability',
            field=models.CharField(choices=[('LOW', 'Baja'), ('MEDIUM', 'Media'), ('HIGH', 'Alta')], default='MEDIUM', max_length=20),
        ),
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Abierta'), ('ANALYSIS', 'En análisis'), ('MITIGATED', 'Mitigada'), ('CLOSED', 'Cerrado')], default='OPEN', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='incident',
            unique_together={('project', 'code')},
        ),
    ]
