# Generated by Django 6.0.5 on 2026-06-14 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0003_incident_links_and_mitigation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='test_case',
        ),
    ]
