# Generated by Django 6.0.5 on 2026-05-26 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testingphase',
            name='completed_tasks',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testingphase',
            name='pending_tasks',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testingphase',
            name='progress',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
