# Generated by Django 6.0.5 on 2026-06-09 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phases', '0002_testingphase_completed_tasks_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='testingphase',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testingphase',
            name='entry_criteria',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='testingphase',
            name='exit_criteria',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='testingphase',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testingphase',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
