# Generated by Django 6.0.5 on 2026-05-26 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testplans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testplan',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='testplan',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testplan',
            name='entry_criteria',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='testplan',
            name='exit_criteria',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='testplan',
            name='resources',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='testplan',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testplan',
            name='version',
            field=models.CharField(default='1.0', max_length=20),
        ),
        migrations.AlterField(
            model_name='testplan',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Borrador'), ('REVIEW', 'En revisión'), ('APPROVED', 'Aprobado'), ('CLOSED', 'Cerrado')], default='DRAFT', max_length=20),
        ),
    ]
