# Generated by Django 6.0.5 on 2026-06-09 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testplans', '0003_testplan_environment_responsibilities_estimation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestPlanVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('version_label', models.CharField(default='1.0', max_length=20)),
                ('name', models.CharField(max_length=180)),
                ('objective', models.TextField()),
                ('status', models.CharField(choices=[('DRAFT', 'Borrador'), ('REVIEW', 'En revisión'), ('APPROVED', 'Aprobado'), ('CLOSED', 'Cerrado')], max_length=20)),
                ('change_reason', models.CharField(blank=True, max_length=180)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('test_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='testplans.testplan')),
            ],
            options={
                'ordering': ['test_plan', '-version_number'],
                'unique_together': {('test_plan', 'version_number')},
            },
        ),
    ]
