# Generated by Django 6.0.5 on 2026-06-14 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testplans', '0004_testplanversion'),
    ]

    operations = [
        migrations.AddField(
            model_name='testplan',
            name='maximum_critical_defects',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='testplan',
            name='minimum_coverage_percentage',
            field=models.PositiveSmallIntegerField(default=90),
        ),
        migrations.AddField(
            model_name='testplan',
            name='minimum_pass_percentage',
            field=models.PositiveSmallIntegerField(default=80),
        ),
        migrations.AddField(
            model_name='testplan',
            name='test_types',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
