# Generated by Django 5.2.15 on 2026-07-31 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testplans', '0006_testplan_base_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testplan',
            name='base_document',
        ),
    ]
